version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: expense_tracker_db
    restart: always
    environment:
      POSTGRES_DB: expense_tracker_db
      POSTGRES_USER: expense_user
      POSTGRES_PASSWORD: expense_password_123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
